databases:
  - name: nk-jobboard_DB
    databaseName: nk_jobboard_db
    user: nk-jobboard
    region: singapore

services:
  - type: web
    name: nk-jobboard
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nk-jobboard_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
